name: Action di Ravizza
on:
  push:
jobs:
  ciao: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo "ciao sono una stringa"
      - run: echo "Io sono Patrick"
      - run: python --version
      - run: ifconfing
      - run: pip --version
      - run: lsb_release -d 
      - run: ls -la
      - run: pwd
      - run: env
 