name: Action di Ravizza
on:
  push:
jobs:
  ciao: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo "ciao sono una stringa"
      - run: echo "Io sono Patrick"
      - run: python --version
      - run: ifconfig
      - run: pip --version
      - run: lsb_release -d 
      - run: ls -la
      - run: pwd
      - run: env
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ravizza
      - run: ls -la
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install pandas scikit-learn numpy matplotlib joblib
      - run: python ml_supervised.py
        working-directory: ravizza
 